
[window]

opacity = 0.7

padding.x = 0
padding.y = 0

decorations = "Full"
decorations_theme_variant = "Light" # "Dark"

[font]

normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"
bold_italic.family = "JetBrainsMono Nerd Font"

size = 11.0

[general]
import = [
    "~/.config/alacritty/themes/themes/blood_moon.toml"
]

